application: mscloud-emendez
module: default
version: 1
runtime: go
api_version: go1
instance_class: F4_1G
automatic_scaling:
  min_idle_instances: 3
  max_idle_instances: 5  
  min_pending_latency: 15ms
  max_pending_latency: 30ms
  max_concurrent_requests: 100
handlers:
- url: /.*
  script: _go_app